### ISSUE TITLE
Target eye in top left of screen.

### ISSUE THREAD

**Issue by l4ndon** [imahdiy/qb-target-nopixel4.0#5]
Theres a target icon in the top left of everyone's screen in the server. I wasn't able to locate where it was coming from, but upon stopping the resource, it went away.

![FiveM_b2944_GTAProcess_Xb2aQphXGU](https://github.com/imahdiy/qb-target-nopixel4.0/assets/113076950/d1774c7b-59b5-4ade-8d64-d34c165d400d)

**Comment by Boom1053** [comment]
https://github.com/imahdiy/qb-target-nopixel4.0/pull/6

fixed it here.

**Comment by Boom1053** [comment]
https://github.com/imahdiy/qb-target-nopixel4.0/pull/6

fixed it here.
